### ISSUE TITLE
Building image from docker file

### ISSUE THREAD

**Issue by mtwest2718** [htcondor/htc-notebook#9]
The current _Quick Start_ in the **ReadMe** presumes you have already built an image.

It may be useful for those not used to working with Docker containers to include a recommended build command so they need not leave the github page to look up other documentation.

**Comment by JoshKarpel** [comment]
The command in the quick start should pull the image from Docker Hub (you don't need to build it locally). The repository isn't really set up for easy non-automated builds of the images, since we didn't expect people to need to be able to do that. Is that a use case you need?

**Comment by mtwest2718** [comment]
Ahhhh OK. Yes that is what the use case I was looking for. Being new to Docker, this wasn't obvious. 
-- thanks
